# Generated by Django 2.1 on 2018-08-03 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_alunos', models.IntegerField()),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('alunos', models.ManyToManyField(to='pessoa.Aluno')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Horario')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Instrutor')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.Modalidade'),
        ),
    ]
