# Generated by Django 2.1 on 2018-08-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
